ruby_project/config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  resources :users
  devise_for :users, skip: :all
  devise_scope :user do
    get "login", to: "sessions#new", as: :new_user_session
    post "login", to: "sessions#create", as: :user_session
    delete "logout", to: "sessions#destroy", as: :destroy_user_session
  end
  resources :productos
  resources :sales, except: [:edit, :update]

  #match "/users/*", to: "application#not_found", via: :all

  # get "up" => "rails/health#show", as: :rails_health_check

end

ruby_project/app/models/producto.rb
class Producto < ApplicationRecord
  before_create :set_last_modification_date
  before_save :set_last_modification_date

  has_many_attached :images, dependent: :destroy
  has_many :sale_products
  has_many :sales, through: :sale_products

  validates :name, presence: { message: "is required" }, length: { in: 10..100, message: "must be between 10 and 100 characters" }
  validates :description, presence: { message: "is required" }, length: { in: 10..100, message: "must be between 10 and 100 characters" }
  validates :unit_price, presence: { message: "is required" }, numericality: { only_integer: true, greater_than: 0, message: "must be greater than 0" }
  validates :available_stock, presence: { message: "is required" }, numericality: { only_integer: true }
  validates :category, presence: { message: "is required" }
  validates :entry_date, presence: { message: "is required" }
  validates :color, format: { with: /\A[a-zA-Z\s]+\z/, message: "only allows letters and spaces" }, allow_blank: true
  validates :size, numericality: { only_integer: true, greater_than: 0 }, allow_blank: true

  validate :validate_entry_date
  validate :must_have_at_least_one_image, on: :create

  def delete_logically!
    update_attribute(:deactivation_date, Date.today)
    update_attribute(:available_stock, 0)
  end

  private

  def set_entry_date
    self.entry_date = Date.today
  end

  def set_last_modification_date
    self.last_modification_date = Date.today
  end

  def validate_entry_date
    if entry_date.present? && entry_date > Date.today
      errors.add(:entry_date, "cannot be in the future")
    end
  end

  def must_have_at_least_one_image
    if images.blank?
      errors.add(:images, "must have at least one image")
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    ["available_stock", "category", "color", "created_at", "deactivation_date", "description", "entry_date", "id", "last_modification_date", "name", "size", "unit_price", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["images_attachments", "images_blobs", "sale_products", "sales"]
  end
end

ruby_project/app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  CATEGORIES = [
    "Activewear", "Athletic Shoes", "Compression Wear", "Sports Bras", "Training Gear",
    "Outerwear", "Yoga Apparel", "Swimwear", "Running Gear", "Sports Accessories",
    "Team Apparel", "Protective Gear", "Winter Sports Gear", "Performance Wear", "Golf Apparel",
  ].freeze

  SEARCH_CATEGORIES = ["All",
                       "Activewear", "Athletic Shoes", "Compression Wear", "Sports Bras", "Training Gear",
                       "Outerwear", "Yoga Apparel", "Swimwear", "Running Gear", "Sports Accessories",
                       "Team Apparel", "Protective Gear", "Winter Sports Gear", "Performance Wear", "Golf Apparel"].freeze

  # GET /productos or /productos.json
  def index
    order_by = params[:order_by] || "name"
    order_direction = params[:order_direction] || "asc"
    if params.dig(:q, :category_eq) == "All"
      params[:q].delete(:category_eq)
    end
    @q = Producto.ransack(params[:q])
    @productos = @q.result(distinct: true).where(deactivation_date: nil).order("#{order_by} #{order_direction}")
    @categories = SEARCH_CATEGORIES
  end

  # GET /productos/1 or /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
    @categories = CATEGORIES
  end

  # GET /productos/1/edit
  def edit
    @product = Producto.find(params[:id])
    @categories = CATEGORIES
  end

  # POST /productos or /productos.json
  def create
    @producto = Producto.new(producto_params)
    @categories = CATEGORIES

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: "The product was successfully added!" }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1 or /productos/1.json
  def update
    @categories = CATEGORIES
    success = false
    respond_to do |format|
      if producto_params[:images].is_a?(Array) && producto_params[:images].any? { |image| image.present? }
        @producto.images.purge
        if @producto.update(producto_params)
          @producto.images.attach(producto_params[:images])
          success = true
        end
      else
        if @producto.update(producto_params.except(:images))
          success = true
        end
      end
      if success
        format.html { redirect_to @producto, notice: "The product was successfully updated!" }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1 or /productos/1.json
  def destroy
    @categories = CATEGORIES
    @producto.delete_logically!

    respond_to do |format|
      format.html { redirect_to productos_path, status: :see_other, notice: "The product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_producto
    @producto = Producto.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def producto_params
    params.expect(producto: [:name, :description, :unit_price, :available_stock, :category, :size, :color, :entry_date, images: []])
  end
end

ruby_project/app/helpers/productos_helper.rb
module ProductosHelper
end

ruby_project/app/views/productos/_edit_form.html.erb
<%= form_with model: @producto, local: true, html: { multipart: true } do |form| %>
  <% if producto.errors.any? %>
    <div style="color: red">
      <ul>
        <% @producto.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label :name, class: "form-control-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :description, class: "form-control-label" %>
    <%= form.textarea :description, class: "form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :unit_price, class: "form-control-label" %>
    <%= form.number_field :unit_price, step: 1, min: 1, class: "form-control", value: @producto.unit_price.to_i %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :available_stock, class: "form-control-label" %>
    <%= form.text_field :available_stock, class: "form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :images, "Upload Images", class: "form-control-label" %>
    <%= form.file_field :images, multiple: true, name: "producto[images][]", class: "form-control" %>
      <% if producto.images.attached? %>
          <div class="img-row">
          <% producto.images.each do |image| %>
            <div class="img-col product-<%= producto.id %>">
              <%= image_tag image, class: "w-100"%>  
            </div>
          <% end %>
          </div>
        <% end %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :category, class: 'w-100' %>
    <%= form.select :category, options_for_select(@categories), class: "" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :size, class: "form-control-label" %>
    <%= form.text_field :size, class: "form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :color, class: "form-control-label" %>
    <%= form.text_field :color, class: "form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :entry_date, class: "form-control-label" %>
    <%= form.date_field :entry_date, class: "form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.submit "Edit this Product", class: "btn btn-primary" %>
      <%= link_to "Back to productos", productos_path, class: "btn btn-secondary" %>
  </div>
<% end %>

ruby_project/app/views/productos/_form.html.erb
<%= form_with model: @producto, local: true, html: { multipart: true } do |form| %>
  <% if producto.errors.any? %>
    <div style="color: red">
      <ul>
        <% @producto.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label :name, class: "form-control-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :description, class: "form-control-label" %>
    <%= form.textarea :description, class: "form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :unit_price, class: "form-control-label" %>
    <%= form.text_field :unit_price, class: "form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :available_stock, class: "form-control-label" %>
    <%= form.text_field :available_stock, class: "form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :images, "Upload Images", class: "form-control-label" %>
    <%= form.file_field :images, multiple: true, name: "producto[images][]", class: "form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :category, class: 'w-100' %>
    <%= form.select :category, options_for_select(@categories), {}, {class: "form-select"} %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :size, class: "form-control-label" %>
    <%= form.text_field :size, class: "form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :color, class: "form-control-label" %>
    <%= form.text_field :color, class: "form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :entry_date, class: "form-control-label" %>
    <%= form.date_field :entry_date, class: "form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.submit "Create Product", class: "btn btn-primary" %>
      <%= link_to "Back to products", productos_path, class: "btn btn-secondary" %>
  </div>
<% end %>

ruby_project/app/views/productos/_producto.html.erb
<div class="row mb-4" id="<%= dom_id producto %>"> <!-- necesario para rails el id -->
<div class="container prod-container mb-1 ">
  <div class="row">
    <div class="col">
      <p>
        <strong>Name:</strong>
        <%= producto.name %>
      </p>
      <p>
        <strong>Description:</strong>
        <%= producto.description %>
      </p>
      <p>
        <strong>Unit price:</strong>
        <%= producto.unit_price %>
      </p>
      <p>
        <strong>Available stock:</strong>
        <%= producto.available_stock %>
      </p>
      <p>
        <strong>Category:</strong>
        <%= producto.category %>
      </p>
      <% if producto&.color %>
        <p>
          <strong>Color:</strong>
          <%= producto.color %>
        </p>
      <% end %>
      <% if producto&.size %>
        <p>
          <strong>Size:</strong>
          <%= producto.size %>
        </p>
      <% end %>
    </div>
    <div class="col">
      <% if producto.images.attached? %>
          <div class="img-row">
          <% producto.images.each do |image| %>
            <div class="img-col product-<%= producto.id %>">
              <%= image_tag image, class: "w-100"%>  
            </div>
          <% end %>
          </div>
        <% end %>
    </div>
    </div>
  </div>
</div>

ruby_project/app/views/productos/edit.html.erb
<% content_for :title, "Editing producto" %>
<div class="row justify-content-center">
  <div id="secondary-div-title" class="col my-4 pt-4 pb-4 bg-body-tertiary text-center">
      <h1 class="display-4 text-muted text-center">Editing a product</h1>
      <%= render 'layouts/current_session' %>
  </div>
</div>
<div>

<%= render "edit_form", producto: @producto %>

ruby_project/app/views/productos/index.html.erb
<% content_for :title, "Products" %>

<div class="row justify-content-between">
    <div class="h1-div col pt-4 pb-4 bg-body-tertiary text-center">
      <h1 class="display-2 text-muted text-center">Products</h1>
      <% if user_signed_in? %>
        <p>Here, you can <span class="text-primary">create</span>, <span class="text-primary">read</span>, <span class="text-primary">update</span>, and <span class="text-primary">delete</span> products from the catalogue.</p>
      <% else %>
        <p>Here, you can <span class="text-primary">read</span> the products from the catalogue.</p>
      <% end %>
      <%= render 'layouts/current_session' %>
    </div>
</div>
<% if user_signed_in? %>
  <div class="row justify-content-center">
    <%= link_to "New product", new_producto_path, class: "btn btn-primary w-25 h-25" %>
  </div>
<% end %>
</br>
<%= search_form_for @q, url: productos_path, method: :get, class: '' do |f| %>
  <div class="flex">
    <div class="row ">
      <%= f.label :name_or_description_cont, "Search any sportswear:", class: 'lead' %>
    </div>
    <div class="row justify-content-between"">
      <div class="col">
        <%= f.label :category_eq, "Category", class: 'w-100' %>
        <%= f.select :category_eq, options_for_select(@categories, params.dig(:q, :category_eq)), {}, { class: "form-select" } %>
      </div>
      <div class="col">
        <%= label_tag :order_by, "Order by", class: 'w-100' %>
        <%= select_tag :order_by, options_for_select([["Name", "name"], ["Created At", "created_at"]], params[:order_by]), class: "form-select" %>
      </div>
      <div class="col">
        <%= label_tag :order_direction, "Order direction", class: 'w-100' %>
        <%= select_tag :order_direction, options_for_select([["Ascending", "asc"], ["Descending", "desc"]], params[:order_direction]), class: "form-select"%>
      </div>
    </div>
    <div class="row">
      <%= f.search_field :name_or_description_cont, placeholder: 'Search...', class: 'form-control m-2 w-50 h-100', value: params.dig(:q, :name_or_description_cont) %>
      <%= f.submit "Search", class: 'btn btn-outline-primary m-2 mb-4 w-25' %>
    </div>
  </div>
<% end %>
<div id="products" >
  <% @productos.each do |producto| %>

      <%= render producto %>
  <% end %>
</div>

ruby_project/app/views/productos/new.html.erb
<% content_for :title, "New product" %>

<div class="row justify-content-center">
  <div id="secondary-div-title" class="col my-4 pt-4 pb-4 bg-body-tertiary text-center">
      <h1 class="display-4 text-muted text-center">Add new product</h1>
      <p>Here, you can add a new product to the catalogue.</p>
      <%= render 'layouts/current_session' %>
  </div>
</div>
<div>

<%= render "form", producto: @producto %>

ruby_project/app/views/productos/show.html.erb
<%= render @producto %>

<div class="d-flex mb-4">
  <%= link_to productos_path, class: 'btn btn-secondary m-2' do %>
    <button type="button" class="btn btn-secondary p-0">Back to products</button>
  <% end %>
  <% if current_user %>
    <%= link_to edit_producto_path(@producto), class: 'btn btn-primary m-2' do %>
      <button type="button" class="btn btn-primary p-0">Edit this product</button>
    <% end %>
    <%= button_to 'Destroy this product', @producto, method: :delete, form: { data: { turbo: true, turbo_confirm: 'Are you sure you want to delete this product?' } }, class: 'btn btn-danger m-2' %>
  <% end %>
</div>