ruby_project/config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  resources :users
  devise_for :users, skip: :all
  devise_scope :user do
    get "login", to: "sessions#new", as: :new_user_session
    post "login", to: "sessions#create", as: :user_session
    delete "logout", to: "sessions#destroy", as: :destroy_user_session
  end
  resources :productos
  resources :sales, except: [:edit, :update]

  #match "/users/*", to: "application#not_found", via: :all

  # get "up" => "rails/health#show", as: :rails_health_check

end

ruby_project/app/views/layouts/_current_session.html.erb
      <% if user_signed_in? %>
        <p>
          You are logged in as: <b><%= current_user.role %></b>
        </p>
      <% end %>

ruby_project/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'Blog Page', root_path, class:'navbar-brand' %>    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 d-flex w-100">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class:'nav-link lead' %>   
        </li>
        <li class="nav-item">
          <%= link_to 'See products', productos_path, class:"nav-link lead" %>
        </li>
        <% if current_user %>
          <li class="nav-item">
            <%= link_to 'See sales', sales_path, class:"nav-link lead" %>
          </li>
          <li class="nav-item">
            <%= link_to 'See users', users_path, class:"nav-link lead" %>
          </li>
          <li class="nav-item ms-auto d-flex">
            <p class="lead m-2 my-0 align-self-center">Hello, <%= link_to current_user.username, user_path(current_user), class: 'text-decoration-none' %>! </p>
           <%= button_to 'Log out', destroy_user_session_path, method: :delete, form: { data: { turbo: true, turbo_confirm: 'Are you sure you want to log out?' } }, class: 'btn btn-primary mt-1' %>
          </li>
        <% else %>
          <li class="nav-item ms-auto">
            <%= button_to 'Log in', new_user_session_path, method: :get,  class:"btn btn-primary mt-1" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

ruby_project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Ruby Project" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "turbo", type: "module" %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </head>

  <body class="min-vh-100">
    <header>
      <%= render "layouts/navbar" %>
    </header>
    <div class="container p5 mt-5">
      <% if notice %>
        <p class="alert alert-primary mt-4"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger mt-4"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>