ruby_project/config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  resources :users
  devise_for :users, skip: :all
  devise_scope :user do
    get "login", to: "sessions#new", as: :new_user_session
    post "login", to: "sessions#create", as: :user_session
    delete "logout", to: "sessions#destroy", as: :destroy_user_session
  end
  resources :productos
  resources :sales, except: [:edit, :update]

  #match "/users/*", to: "application#not_found", via: :all

  # get "up" => "rails/health#show", as: :rails_health_check

end

ruby_project/app/models/sale.rb
class Sale < ApplicationRecord
  attr_accessor :products_chosen, :products_db

  has_many :sale_products, dependent: :destroy
  has_many :products, through: :sale_products

  # irrelevant
  # validates :total_amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :client_id, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validate :must_have_at_least_one_product_and_correct_amount, on: :create

  before_update :restock_products, if: :will_save_change_to_deleted_at?

  scope :active, -> { where(deleted_at: nil) }

  def destroy
    update(deleted_at: Time.current)
  end

  def deleted?
    deleted_at.present?
  end

  private

  def restock_products
    sale_products.each do |sale_product|
      product = sale_product.product
      if product.deactivation_date != nil
        product.available_stock += sale_product.amount
        product.save!(validate: false)
      end
    end
  end

  def must_have_at_least_one_product_and_correct_amount
    # first, I check there's at least one product in the array
    if products_chosen.nil? || products_chosen.empty?
      errors.add(:base, "At least one product must be sold")
    end

    # then, for each product, I check the amount sold is correct
    products_chosen.each do |product_id, amount|
      if amount.to_i <= 0
        errors.add(:base, "The amount sold must be greater than 0")
      end
      if amount.to_i > products_db[product_id.to_i]
        errors.add(:base, "The amount sold exceeds the available stock for product #{Producto.find(product_id).name}")
      end
    end
  end
end

ruby_project/app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /sales or /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1 or /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
    @products = Producto.all
  end

  # GET /sales/1/edit
  def edit
    # You cannot edit a sale
  end

  # POST /sales or /sales.json
  def create
    @sale = Sale.new(sale_params)
    @sale.products_chosen = extract_product_params
    @sale.products_db = Producto.where(id: @sale.products_chosen.keys).pluck(:id, :available_stock).to_h
    @products = Producto.all

    respond_to do |format|
      if @sale.valid?
        ActiveRecord::Base.transaction do
          @sale.total_amount = 0
          chosen_products = []

          @products.each do |product|
            amount_sold = params["product-#{product.id}"].to_i
            next if amount_sold <= 0

            if amount_sold > product.available_stock
              raise ActiveRecord::Rollback
            end

            sale_product = @sale.sale_products.build(
              product: product,
              amount: amount_sold,
              total_amount: amount_sold * product.unit_price,
            )

            @sale.total_amount += sale_product.total_amount
            product.available_stock -= amount_sold
            product.save!(validate: false) # saltamos las validaciones de Producto ya que no necesitamos validarlas aquí
            chosen_products << sale_product
          end
          @sale.save
        end
        format.html { redirect_to @sale, notice: "The sale was successfully added!" }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1 or /sales/1.json
  def update
    # You cannot edit a sale
  end

  # DELETE /sales/1 or /sales/1.json
  def destroy
    @sale.destroy

    respond_to do |format|
      format.html { redirect_to sales_path, status: :see_other, notice: "Sale was successfully canceled." }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_sale
    @sale = Sale.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def sale_params
    params.expect(sale: [:total_amount, :client_id])
  end

  def extract_product_params
    product_params = {}
    params.each do |key, value|
      if key.start_with?("product-") and value.present?
        product_id = key.split("-").last.to_i
        amount = value.to_i
        product_params[product_id] = amount if amount > 0
      end
    end
    product_params
  end
end

ruby_project/app/helpers/sales_helper.rb
module SalesHelper
end

ruby_project/app/views/sales/_form.html.erb
<%= form_with(model: sale) do |form| %>
  <% if sale.errors.any? %>
    <div style="color: red">
      <ul>
        <% sale.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :client_id, class: "form-control-label" %>
    <%= form.text_field :client_id, class: "form-control" %>
  </div>

  <h2>Products</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Description</th>
        <th>Unit Price</th>
        <th>Stock Available</th>
        <th>Amount Sold</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.id %></td>
          <td><%= product.name %></td>
          <td><%= truncate(product.description, length: 50) %></td>
          <td><%= product.unit_price %></td>
          <td><%= product.available_stock %></td>
          <td>
            <%= number_field_tag "product-#{product.id}", nil, min: 0, max: product.available_stock, disabled: product.available_stock.zero? %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="actions">
    <%= form.submit "Create Sale", class: "btn btn-primary mb-4" %>
    <%= link_to "Back to sales", sales_path, class: "btn btn-secondary mb-4" %>
  </div>
<% end %>

ruby_project/app/views/sales/_sale.html.erb
<div class="row" id="<%= dom_id sale %>">
  <div class="container prod-container mb-1">
    <div class="row">
      <div class="col">
        <h1 class="lead text-center">Sale <%= sale.id %> Details</h1>
        <p class="lead mb-0">Sold to Client: <%= sale.client_id %></p>
        <h2 class="lead">List of products sold:</h2>
        <% sale.sale_products.each do |sale_product| %>
          <div class="product">
            <h4 class="font-weight-bold"><%= sale_product.product.name %></h3>
            <p class="lead m-0">Description: <%= sale_product.product.description %></p>
            <p class="lead m-0">Amount sold: <span class="font-weight-bold"><%= sale_product.amount %></span></p>
            <p class="lead m-0">Total for this product: <%= number_to_currency(sale_product.total_amount) %></p>
          </div>
        <% end %>

        <h2>Total for this sale: <%= number_to_currency(sale.total_amount) %></h2>
      </div>
      <div class="col">
        <% sale.sale_products.each do |sale_product| %>
          <div class="img-row">
            <% sale_product.product.images.each do |image| %>
                <div class="img-col product-<%= sale_product.product.id %>">
                  <%= image_tag image, class: "w-100"%>  
                </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

ruby_project/app/views/sales/index.html.erb
<% content_for :title, "Sales" %>
<div class="row justify-content-between">
    <div class="h1-div col pt-4 pb-4 bg-body-tertiary text-center">
      <h1 class="display-2 text-muted text-center">Sales</h1>
      <p>Here, you can <span class="text-primary">create</span>, <span class="text-primary">read</span> or <span class="text-primary">cancel</span> sales from the database.</p>
      <%= render 'layouts/current_session' %>
    </div>
</div>
<div class="row justify-content-center">
  <%= link_to "New sale", new_sale_path, class: "btn btn-primary w-25 h-25" %>
</div>
<div id="sales">
  <% @sales.active.each do |sale| %>
    <%= render sale %>
    <p>
      <%= link_to "Show this sale", sale %>
    </p>
  <% end %>
</div>

ruby_project/app/views/sales/new.html.erb
<% content_for :title, "New sale" %>

<div class="row justify-content-center">
  <div id="secondary-div-title" class="col my-4 pt-4 pb-4 bg-body-tertiary text-center">
      <h1 class="display-4 text-muted text-center">Add new sale</h1>
      <p>Here, you can register a new sale.</p>
      <%= render 'layouts/current_session' %>
  </div>
</div>
<div>

<%= render "form", sale: @sale %>

ruby_project/app/views/sales/show.html.erb
<%= render @sale %>

<div class="d-flex mb-4">
  <%= link_to sales_path, class: 'btn btn-secondary m-2' do %>
    <button type="button" class="btn btn-secondary p-0">Back to sales</button>
  <% end %>

  <%= button_to 'Cancel sale', sales_path(@sale), method: :delete, form: { data: { turbo: true, turbo_confirm: 'Are you sure you want to cancel this sale?' } }, class: 'btn btn-danger m-2' %>
</div>